server {
    listen 80;
    listen [::]:80;

    server_name vepo.in www.vepo.in;
    root /var/www/vepo.in;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|html)$ {
        add_header Cache-Control "no-cache";
    }
}